version: '3'

services:

  stateless-auth-db:
    container_name: statless-auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - auth

  stateful-auth-db:
    container_name: statful-auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - auth


  token-redis:
    container_name: token-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - auth

  stateless-auth-api:
    build: './stateless/stateless-auth-api'
    container_name: stateless-auth-api
    depends_on:
      - stateless-auth-db
    environment:
      - PORT=8080
      - DB_HOST=stateless-auth-db
      - DB_PORT=5432
      - DB_NAME=auth-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8080:8080"
    networks:
      - auth

  stateless-any-api:
    build: './stateless/stateless-any-api'
    container_name: stateless-any-api
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
    networks:
      - auth

  stateful-auth-api:
    build: './stateful/stateful-auth-api'
    container_name: stateful-auth-api
    depends_on:
      - stateful-auth-db
    environment:
      - PORT=8082
      - DB_HOST=stateful-auth-db
      - DB_PORT=5432
      - DB_NAME=auth-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8082:8082"
    networks:
      - auth

  stateful-any-api:
    build: './stateful/stateful-any-api'
    container_name: stateful-any-api
    environment:
      - PORT=8083
    ports:
      - "8083:8083"
    networks:
      - auth


networks:
  auth:
    driver: bridge